alias open="explorer.exe"
alias pip="uv pip"
alias pip3="uv pip"
alias python="python3"
alias nvm="fnm"
alias cat="bat"
alias diff="delta"
alias grep="rg"
alias code="code"
alias top="htop"
alias curl="curlie"
alias du="dust"
alias loc="scc"
alias neofetch="fastfetch"
alias dns="doggo"
alias ls="eza"
alias l="ls"
alias calc="qalc"

# Docker aliases
alias d="docker"
alias dc="docker compose"
alias dce="docker compose exec"
alias dcu="docker compose up --build -d"
alias dcr="docker compose restart"
alias dcd="docker compose down"
alias dcl="docker compose logs -f"

# Git aliases
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias git-restart="git reset HEAD --hard"

alias ls="eza --group-directories-first --icons=never --git --smart-group"
