alias -- -="cd -"
alias open="explorer.exe"
alias pip="uv pip"
alias pip3="uv pip"
alias python="python3"
alias nvm="fnm"
alias cat="bat"
alias diff="delta"
alias grep="rg"
alias code="nocorrect code"
alias top="htop"
alias curl="curlie"
alias test="nocorrect test"
alias du="dust"
alias loc="scc"
alias neofetch="fastfetch"

# Docker aliases
alias d="docker"
alias dc="docker compose"
alias dce="docker compose exec"
alias dcu="docker compose up --build -d"
alias dcr="docker compose restart"
alias dcd="docker compose down"
alias dcl="docker compose logs -f"
